name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "9d8c930c91be4dc79fb1f13f37574cf1" },
  { binding = "SHARE", id = "2aa0f2dd12c34497bc3eca6dfc2e750b" }
]